package cn.itcast.byecode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-10-14T18:04:52.308+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://inter.server.itcast.cn/", name = "ByeInter")
@XmlSeeAlso({ObjectFactory.class})
public interface ByeInter {

    @WebMethod
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://inter.server.itcast.cn/", className = "cn.itcast.byecode.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://inter.server.itcast.cn/", className = "cn.itcast.byecode.SayByeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayBye(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
